---
title: "Week 1"
#bibliography: references.bib
author: "Kalle Stoffers"
---

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

------------------------------------------------------------------------

The principle of homophily refers to the larger likelihood of observing a positive relationship between two people who are similar. In the world of academic research, this principle also applies. For example, we see that researchers with greater physical proximity or the same gender are more likely to collaborate (Horta et al., 2022). Given the different positions researchers can hold in universities, this raises the following descriptive research question:

(Descriptive) RQ1: To what degree does position homophily/clustering occur among social science researchers in the Netherlands?

It has been well-established that one's social network can provide resources which can be advantageous, for example in finding a job. Research shows that network centrality does explain finding prestigious jobs (Hadani et al., 2012). No association was found with regards to career publications. However, in this paper, network centrality was defined by graduating from more centrally located departments. This brings us to the question: what is the impact on the homophily structure in terms of position on the citations of researchers?

(Explanatory) RQ2: How does the network composition in terms of position influence a researcher's citations?

------------------------------------------------------------------------

# References

Hadani, M., Coombes, S., Das, D. and Jalajas, D. (2012), Finding a good job: Academic network centrality and early occupational outcomes in management academia. J. Organiz. Behav., 33: 723-739. <https://doi.org/10.1002/job.788>

Horta, H., Feng, S. & Santos, J.M. Homophily in higher education research: a perspective based on co-authorships. Scientometrics 127, 523–543 (2022). <https://doi.org/10.1007/s11192-021-04227-z>
