---
title: "Week 3"
author: "Kalle Stoffers"
date: "2025-09-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#In class

```{r}


rm(list = ls())

#Custom functions
fpackage.check <- function(packages) {
    lapply(packages, FUN = function(x) {
        if (!require(x, character.only = TRUE)) {
            install.packages(x, dependencies = TRUE)
            library(x, character.only = TRUE)
        }
    })
}

fsave <- function(x, file = NULL, location = "./data/processed/") {
    ifelse(!dir.exists("data"), dir.create("data"), FALSE)
    ifelse(!dir.exists("data/processed"), dir.create("data/processed"), FALSE)
    if (is.null(file))
        file = deparse(substitute(x))
    datename <- substr(gsub("[:-]", "", Sys.time()), 1, 8)
    totalname <- paste(location, datename, file, ".rda", sep = "")
    save(x, file = totalname)  #need to fix if file is reloaded as input name, not as x. 
}

fload <- function(filename) {
    load(filename)
    get(ls()[ls() != "filename"])
}

fshowdf <- function(x, ...) {
    knitr::kable(x, digits = 2, "html", ...) %>%
        kableExtra::kable_styling(bootstrap_options = c("striped", "hover")) %>%
        kableExtra::scroll_box(width = "100%", height = "300px")
}

packages <- c("tidyverse", "scholar", "openalexR", "rvest", "jsonlite")
fpackage.check(packages)

url <- "https://api.openalex.org/authors?search=Jochem Tolsma"

jt_json <- fromJSON("https://api.openalex.org/authors?search=Jochem+Tolsma", simplifyVector = FALSE)
glimpse(jt_json, max.level = 1)

str(jt_json$results,2)
  
  

jt_json[["results"]][[1]]$affiliations[[1]]$institution$display_name

#df <- read_xlsx ("C:/Users/kalle/OneDrive/Documenten/REMA/Jaar 2/Social Networks/KS_labjournal/data/20240419Scholarid_soc_pol.xlsx")


```



#Homework

```{r}
rm(list = ls())

library(tidyverse)
#install.packages("openalexR")
library(openalexR)

df <- readxl::read_excel("C:/Users/kalle/OneDrive/Documenten/REMA/Jaar 2/Social Networks/KS_labjournal/data/20240419Scholarid_soc_pol.xlsx")


mail <- "kalle.stoffers@ru.nl"


#empty list
citations_all <- list()

remaining_authors <- df$Naam[(length(citations_all) + 1):length(df$Naam)]

for (author_name in remaining_authors) {

#fetch information
search <- tryCatch({
  oa_fetch(
  entity = "authors",
  search = author_name,
  mailto = mail)
}, error = function(e) {
    message("Error with author: ", df$Naam[i])
    return(NULL)
  })

if (is.null(search) || nrow(search) == 0) {
    next
  }

#first result only
author_data <- search[1, ]

#if there is no data
counts <- author_data$counts_by_year

if (!is.list(counts) || length(counts) == 0 || !is.data.frame(counts[[1]])) {
  message("Skipping author with invalid counts_by_year: ", author_data$display_name)
  next
}

#select relevant info
df_citations <- author_data$counts_by_year[[1]] |>
  select(year, cited_by_count) |>
  mutate(Naam = author_data$display_name) |>
  relocate(Naam) |>
  pivot_wider(names_from = year, values_from = cited_by_count)

#add to list
citations_all[[author_name]] <- df_citations

}

#put all rows together
df_citations_total <- bind_rows(citations_all)
str(df_citations_total)

#merge with OG dataset  
df <- left_join(df, df_citations_total, by = "Naam")

str(df)
view(df)

#Descriptives?

summary(df)


```


# (Updated) RQs
(Descriptive) RQ1: To what degree is there position homophily in publication collaberations between social science researchers in the Netherlands? 

(Explanatory) RQ2: How does the position composition of a researcher's egonet (paper collaberations / department) influence a researcher's citations?

